ros:
  subscriber_topic_wheel: "/wheel_states"
  publisher_topic_A: "aaaaa"

# TODO le velocita delle bag sono in rad/min
robot:
  params:
    r: 10
    l: 10
    w: 11
    CPR: 88 #encoder
    gearRation: 5

  initial_pose:
    x: 0.0
    y: 0.0
    theta: 0.0